site_name: Telmi Wiki
site_description: Partage de connaissance de la communautÃ© Telmi !
repo_name: heuzef/telmi-wiki
copyright: Telmi Interactive

nav:
  - âœ¨ Accueil: index.md
  - ğŸ›ï¸ Stores:
      - Stores internationaux: stores/stores_internationaux.md
      - Stores privÃ©s: stores/stores_prives.md
      - CrÃ©er son Store Telmi: stores/creer_son_store_telmi.md
      - HÃ©berger son Store Telmi: stores/heberger_son_store_telmi.md
  - ğŸ’³ Achats:
      - Miyoo Mini Plus: achats/miyoo_mini_plus.md
      - Carte Micro SD: achats/carte_micro_sd.md
  - ğŸ­ Cultures:
      - Page en construction: wip.md
  - ğŸª„ CrÃ©ations:
      - Charte graphique Telmi: creations/charte_graphique_telmi.md
      - Images de chapitre: creations/images_de_chapitre.md
  - ğŸª› Bricolages:
      - DÃ©tails techniques de la Miyoo Mini Plus: bricolages/details_techniques_de_la_miyoo_mini_plus.md
  - ğŸš€ Developments:
      - Astuces Telmi-Sync: developments/astuces_telmi_sync.md
      - Installation manuelle TelmiOS sur Linux: developments/installation_manuelle_telmios_sur_linux.md
      - Installation manuelle TelmiOS sur Windows: developments/installation_manuelle_telmios_sur_windows.md
      - Guide du developpeur Telmi-OS: developments/guide_du_developpeur_telmi-os.md
      - Documentation du format des histoires telmi: developments/documentation_du_format_des_histoires_telmi.md

theme:
  name: dracula
  logo: assets/img/telmi-wiki.png
  favicon: assets/img/favicon.ico
