site_name: Telmi Wiki
site_description: Partage de connaissance de la communautÃ© Telmi !
repo_name: heuzef/telmi-wiki
copyright: Telmi Interactive

nav:
    - âœ¨ Accueil: index.md
    - ğŸ›ï¸ Stores: 
      - Stores internationaux: stores/stores_internationaux.md
      - Stores privÃ©s: stores/stores_prives.md
      - CrÃ©er son Store Telmi: stores/creer_son_store_telmi.md
      - HÃ©berger son Store Telmi: stores/heberger_son_store_telmi.md
    - ğŸ’³ Achats:
      - Miyoo Mini Plus: achats/miyoo_mini_plus.md
      - Carte SD: achats/carte_sd.md
    - ğŸ­ Cultures:
      - Page en construction : wip.md
    - ğŸª„ CrÃ©ations:
      - Charte graphique Telmi : creations/charte_graphique_telmi.md
    - ğŸª› Bricolages:
      - DÃ©tails techniques de la Miyoo Mini Plus : bricolages/details_techniques_de_la_miyoo_mini_plus.md
    - ğŸš€ Developments:
      - Installation manuel TelmiOS sur Linux : developments/installation_manuelle_telmios_sur_linux.md

theme:
  name: dracula
  logo: assets/img/telmi-wiki.png
  favicon: assets/img/favicon.ico