site_name: Telmi Wiki
site_description: Partage de connaissance de la communautÃ© Telmi !
repo_name: heuzef/telmi-wiki
copyright: Telmi Interactive

nav:
    - âœ¨ Accueil: index.md
    - ğŸ›ï¸ Stores: 
      - CrÃ©er un store : stores/creer_un_store_telmi.md
      - Stores internationaux : stores/stores_internationaux.md
    - ğŸ’³ Achats :
      - Miyoo Mini Plus : achats/miyoo_mini_plus.md
      - Carte SD : achats/carte_sd.md

theme:
  name: dracula
  logo: assets/img/telmi-wiki.png
  favicon: assets/img/favicon.ico